### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by Kane-LAU** [GengxinLiu/SWMP#1]
Thanks for your contribution. GOOD WORK!    
But I find  the repo missed requirement.txt, could you provide the material ? 

Thanks in advance!!!

**Comment by Kane-LAU** [comment]
@GengxinLiu

**Comment by GengxinLiu** [comment]
@Kane-LAU Done

**Comment by Kane-LAU** [comment]
> @Kane-LAU Done

THANK YOU! 😀
